name: "01-EKS"
on:
  push:
    branches:
      - 'main'

jobs:
  Plan:
    uses: prem1903/eksterraform/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: main
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: prem1903/eksterraform/.github/workflows/aws_tf_appy.yml@main
    with:
      gh_environment: main
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
